import React, { createContext, useContext, useState } from 'react';

export type Language = 'EN' | 'GU' | 'HI';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'platform.title': 'KAUSHALSETU',
    'platform.subtitle': 'Gujarat',
    'platform.tagline': '“Tracking Outcomes. Building Skills.”',
    'nav.home': 'Home',
    'nav.about': 'About the Platform',
    'nav.programmes': 'Programmes',
    'nav.track': 'Track Outcome',
    'nav.contact': 'Contact',
    'nav.login': 'Login / Register',
    'nav.logout': 'Logout',
    'nav.my_dashboard': 'My Dashboard',
    'nav.go_to_dashboard': 'Go to Dashboard',
    'role.trainee': 'Trainee',
    'role.employer': 'Employer',
    'role.provider': 'Training Provider',
    'role.government': 'Government Portal',
    'role.trainee.action': 'Log in to verify check-ins',
    'role.employer.action': 'Verify employment & feedback',
    'role.provider.action': 'Track batches & placements',
    'role.government.action': 'View dashboard & intelligence',
    'stats.trainees': 'Trainees Tracked',
    'stats.retention': '6-Month Retention',
    'stats.districts': 'Districts Covered',
    'stats.flagged': 'Programmes Flagged',
    'gov.india': 'Government of India',
    'gov.gujarat': 'Government of Gujarat',
    'satyameva': 'Satyameva Jayate',
    'login.title': 'Secure Authorization',
    'login.welcome': 'Sign in to access your role-specific dashboard.',
    'login.email': 'Email / Username',
    'login.password': 'Password',
    'login.button': 'Authenticate',
    'login.forgot': 'Forgot Password?',
    'login.back': 'Back to Role Selection',
    'footer.det': 'Directorate of Employment & Training (DET), Gandhinagar',
    'footer.copy': '© 2026 KaushalSetu – Gujarat. All rights reserved. (Synthetic Demo Site)',
    'footer.links': 'Privacy Policy | Terms of Service | Helpdesk',
    'home.select_role': 'Select Portal Entry Point',
    'home.authorized_login': 'Authorized Login',
    'home.lifecycle_title': 'Platform Tracking Lifecycle',
    'home.lifecycle_subtitle': 'How KaushalSetu continuously tracks training-to-employment loops',
    'home.metrics_title': 'Current Ecosystem Metrics',
    'home.disclaimer_title': 'Synthetic Project Demonstration Notice',
    'home.disclaimer_desc': 'All trainee registrations, corporate verification records, and dashboard metrics displayed on this site are synthetically generated mock models. They do not represent actual data collected by the Government of Gujarat or any registered industrial candidates.',
    'home.enables_title': 'What KaushalSetu Enables',
    'home.enables.track': 'TRACK',
    'home.enables.track_desc': 'Trainee outcomes over time',
    'home.enables.verify': 'VERIFY',
    'home.enables.verify_desc': 'Employment records with employers',
    'home.enables.improve': 'IMPROVE',
    'home.enables.improve_desc': 'Training through real feedback',
    'home.enables.decide': 'DECIDE',
    'home.enables.decide_desc': 'Government data intelligence',
    'step1.title': 'Vocational Training',
    'step1.desc': 'Graduates complete certified ITI/skill courses.',
    'step2.title': 'Employment Placement',
    'step2.desc': 'Trainees enter the workforce across industries.',
    'step3.title': '3-Month Check-in',
    'step3.desc': 'Trainee updates placement and wage details.',
    'step4.title': '6-Month Check-in',
    'step4.desc': 'Verification of retention and role growth.',
    'step5.title': '12-Month Check-in',
    'step5.desc': 'Longitudinal stability tracking completed.',
    'step6.title': 'Employer Verification',
    'step6.desc': 'Industry HR confirms details and logs skill gaps.',
    'step7.title': 'Government Analytics',
    'step7.desc': 'DET monitors district and provider outcomes.',
    'step8.title': 'Policy Optimization',
    'step8.desc': 'Curriculum corrected based on skill gaps.',
    'about.title': 'ABOUT KAUSHALSETU',
    'about.subtitle': '“Understanding Gujarat’s employment-outcome ecosystem”',
    'about.what_is_desc': 'KaushalSetu tracks what happens after skill training — from employment and retention to employer feedback and emerging skill gaps.',
    'about.challenge_title': 'THE CHALLENGE',
    'about.challenge.placement': 'PLACEMENT ≠ RETENTION',
    'about.challenge.placement_desc': 'Getting a job is only the first step.',
    'about.challenge.skills': 'SKILLS ≠ ALWAYS JOB-READY',
    'about.challenge.skills_desc': 'Workplace requirements can change.',
    'about.challenge.followup': 'LIMITED FOLLOW-UP',
    'about.challenge.followup_desc': 'Long-term outcomes need continuous tracking.',
    'about.solves_title': 'HOW KAUSHALSETU SOLVES IT',
    'about.roles_title': 'ONE ECOSYSTEM. FOUR ROLES.',
    'about.role.trainee_desc': 'Updates employment outcomes and check-ins.',
    'about.role.employer_desc': 'Verifies employment and provides workplace feedback.',
    'about.role.provider_desc': 'Tracks programme performance and outcomes.',
    'about.role.government_desc': 'Uses aggregated intelligence for better decisions.',
    'about.lifecycle_title': 'FROM DATA TO DECISION',
    'about.cycle.collect': 'COLLECT',
    'about.cycle.collect_desc': 'Employment + check-in + employer data',
    'about.cycle.analyse': 'ANALYSE',
    'about.cycle.analyse_desc': 'Retention + mismatch + skill gaps',
    'about.cycle.act': 'ACT',
    'about.cycle.act_desc': 'Improve programmes and policy decisions',
    'about.why_title': 'WHY IT MATTERS',
    'about.why.tracking': 'BETTER OUTCOME TRACKING',
    'about.why.feedback': 'STRONGER INDUSTRY FEEDBACK',
    'about.why.development': 'DATA-INFORMED SKILL DEVELOPMENT',
    'about.final_statement': '“From training outcomes to better decisions for Gujarat.”',
    'header.det_title': 'Directorate of Employment & Training',
    'footer.brand_title': 'KaushalSetu – Gujarat',
    'footer.brand_desc': 'Longitudinal vocational outcome tracking engine. A data-driven system to empower youth employment, monitor provider quality, and optimize statewide skills policy.',
    'footer.tag': 'Gujarat Skill Development Directorate',
    'footer.contact_title': 'Official Contact',
    'footer.address': 'Block No. 1, 3rd Floor, Dr. Jivraj Mehta Bhavan, Gandhinagar - 382010',
    'footer.links_title': 'Government Portals',
    'footer.link.state': 'Gujarat State Portal',
    'footer.link.det': 'DET Gujarat Portal',
    'footer.link.msde': 'Ministry of Skill Development (MSDE)',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.help': 'Helpdesk',
  },
  GU: {
    'platform.title': 'કૌશલસેતુ',
    'platform.subtitle': 'ગુજરાત',
    'platform.tagline': '“રોજગાર ટ્રેકિંગ. કૌશલ્ય નિર્માણ.”',
    'nav.home': 'હોમ',
    'nav.about': 'પ્લેટફોર્મ વિશે',
    'nav.programmes': 'કાર્યક્રમો',
    'nav.track': 'પરિણામ ટ્રેક કરો',
    'nav.contact': 'સંપર્ક',
    'nav.login': 'લોગીન / રજીસ્ટર',
    'nav.logout': 'લોગઆઉટ',
    'nav.my_dashboard': 'મારું ડેશબોર્ડ',
    'nav.go_to_dashboard': 'ડેશબોર્ડ પર જાઓ',
    'role.trainee': 'તાલીમાર્થી',
    'role.employer': 'નિયોક્તા',
    'role.provider': 'તાલીમ પ્રદાતા',
    'role.government': 'સરકારી પોર્ટલ',
    'role.trainee.action': 'ચેક-ઇન્સ ચકાસવા માટે લોગઇન કરો',
    'role.employer.action': 'રોજગાર વેરિફિકેશન અને પ્રતિસાદ',
    'role.provider.action': 'બેચ અને પ્લેસમેન્ટ ટ્રેક કરો',
    'role.government.action': 'ડેશબોર્ડ અને ઇન્ટેલિજન્સ જુઓ',
    'stats.trainees': 'ટ્રેક કરેલા તાલીમાર્થીઓ',
    'stats.retention': '૬-મહિનાની જાળવણી',
    'stats.districts': 'આવરી લીધેલ જિલ્લાઓ',
    'stats.flagged': 'ફ્લેગ કરેલા કાર્યક્રમો',
    'gov.india': 'ભારત સરકાર',
    'gov.gujarat': 'ગુજરાત સરકાર',
    'satyameva': 'સત્યમેવ જયતે',
    'login.title': 'સુરક્ષિત લોગીન',
    'login.welcome': 'તમારા રોલ-વિશિષ્ટ ડેશબોર્ડને ઍક્સેસ કરવા સાઇન ઇન કરો.',
    'login.email': 'ઈમેલ / યુઝરનેમ',
    'login.password': 'પાસવર્ડ',
    'login.button': 'પ્રમાણિત કરો',
    'login.forgot': 'પાસવર્ડ ભૂલી ગયા છો?',
    'login.back': 'રોલ પસંદગી પર પાછા જાઓ',
    'footer.det': 'રોજગાર અને તાલીમ નિયામકની કચેરી (DET), ગાંધીનગર',
    'footer.copy': '© ૨૦૨૬ કૌશલસેતુ – ગુજરાત. સર્વાધિકાર સુરક્ષિત. (પરીક્ષણ સાઇટ)',
    'footer.links': 'ગોપનીયતા નીતિ | સેવાની શરતો | હેલ્પડેસ્ક',
    'home.select_role': 'પોર્ટલ પ્રવેશ બિંદુ પસંદ કરો',
    'home.authorized_login': 'અધિકૃત લોગીન',
    'home.lifecycle_title': 'પ્લેટફોર્મ ટ્રેકિંગ લાઈફસાઈકલ',
    'home.lifecycle_subtitle': 'કૌશલસેતુ કઈ રીતે તાલીમથી રોજગાર સુધી સતત ટ્રેકિંગ કરે છે',
    'home.metrics_title': 'વર્તમાન ઇકોસિસ્ટમ આંકડા',
    'home.disclaimer_title': 'પરીક્ષણ પ્રોજેક્ટ ડેમો સૂચના',
    'home.disclaimer_desc': 'આ સાઇટ પર પ્રદર્શિત તમામ તાલીમાર્થીઓની નોંધણી, કોર્પોરેટ વેરિફિકેશન રેકોર્ડ્સ અને ડેશબોર્ડ મેટ્રિક્સ કાલ્પનિક રીતે જનરેટ કરવામાં આવ્યા છે. તે ગુજરાત સરકાર દ્વારા એકત્રિત કરવામાં આવેલ વાસ્તવિક ડેટાનું પ્રતિનિધિત્વ કરતા નથી.',
    'home.enables_title': 'કૌશલસેતુ શું સક્ષમ કરે છે',
    'home.enables.track': 'ટ્રેક',
    'home.enables.track_desc': 'સમય સાથે તાલીમાર્થીઓના પરિણામો',
    'home.enables.verify': 'વેરિફાય',
    'home.enables.verify_desc': 'એમ્પ્લોયરો સાથે રોજગાર રેકોર્ડ્સ',
    'home.enables.improve': 'સુધારો',
    'home.enables.improve_desc': 'વાસ્તવિક પ્રતિસાદ દ્વારા તાલીમ',
    'home.enables.decide': 'નિર્ણય',
    'home.enables.decide_desc': 'સરકારી ડેટા ઇન્ટેલિજન્સ',
    'step1.title': 'વ્યવસાયિક તાલીમ',
    'step1.desc': 'સ્નાતકો પ્રમાણિત ITI / કૌશલ્ય અભ્યાસક્રમો પૂર્ણ કરે છે.',
    'step2.title': 'રોજગાર પ્લેસમેન્ટ',
    'step2.desc': 'તાલીમાર્થીઓ વિવિધ ઉદ્યોગોમાં કાર્યબળમાં પ્રવેશ કરે છે.',
    'step3.title': '૩-મહિનાનું ચેક-ઇન',
    'step3.desc': 'તાલીમાર્થી પ્લેસમેન્ટ અને પગાર વિગતો અપડેટ કરે છે.',
    'step4.title': '૬-મહિનાનું ચેક-ઇન',
    'step4.desc': 'જાળવણી અને ભૂમિકા વિકાસની ચકાસણી.',
    'step5.title': '૧૨-મહિનાનું ચેક-ઇન',
    'step5.desc': 'લાંબા ગાળાની સ્થિરતા ટ્રેકિંગ પૂર્ણ થયું.',
    'step6.title': 'નિયોક્તા વેરિફિકેશન',
    'step6.desc': 'ઉદ્યોગ HR વિગતોની પુષ્ટિ કરે છે અને કૌશલ્ય ખાધની નોંધ કરે છે.',
    'step7.title': 'સરકારી વિશ્લેષણ',
    'step7.desc': 'DET જિલ્લા અને પ્રદાતા પરિણામો પર નજર રાખે છે.',
    'step8.title': 'નીતિ ઓપ્ટિમાઇઝેશન',
    'step8.desc': 'કૌશલ્ય ખાધના આધારે અભ્યાસક્રમમાં સુધારો કરવામાં આવે છે.',
    'about.title': 'કૌશલસેતુ વિશે',
    'about.subtitle': '“ગુજરાતના રોજગાર-પરિણામ ઇકોસિસ્ટમને સમજવું”',
    'about.what_is_desc': 'કૌશલસેતુ તાલીમ પછી શું થાય છે તે ટ્રેક કરે છે - રોજગાર અને જાળવણીથી લઈને નિયોક્તાના પ્રતિસાદ અને ઉભરતી કૌશલ્ય ખાધ સુધી.',
    'about.challenge_title': 'પડકાર',
    'about.challenge.placement': 'પ્લેસમેન્ટ ≠ જાળવણી',
    'about.challenge.placement_desc': 'નોકરી મેળવવી એ માત્ર પ્રથમ પગલું છે.',
    'about.challenge.skills': 'કૌશલ્ય ≠ હંમેશા નોકરી માટે તૈયાર',
    'about.challenge.skills_desc': 'કાર્યસ્થળની જરૂરિયાતો બદલાઈ શકે છે.',
    'about.challenge.followup': 'મર્યાદિત ફોલો-અપ',
    'about.challenge.followup_desc': 'લાંબા ગાળાના પરિણામો માટે સતત ટ્રેકિંગ જરૂરી છે.',
    'about.solves_title': 'કૌશલસેતુ તેનું નિરાકરણ કેવી રીતે કરે છે',
    'about.roles_title': 'એક ઇકોસિસ્ટમ. ચાર ભૂમિકાઓ.',
    'about.role.trainee_desc': 'ચેક-ઇન્સ અને રોજગાર પરિણામો અપડેટ કરે છે.',
    'about.role.employer_desc': 'રોજગાર ચકાસે છે અને કાર્યસ્થળ પ્રતિસાદ આપે છે.',
    'about.role.provider_desc': 'પ્રોગ્રામ પ્રદર્શન અને પરિણામો ટ્રેક કરે છે.',
    'about.role.government_desc': 'વધુ સારા નિર્ણયો માટે એકત્રિત ઇન્ટેલિજન્સનો ઉપયોગ કરે છે.',
    'about.lifecycle_title': 'ડેટાથી નિર્ણય સુધી',
    'about.cycle.collect': 'એકત્ર કરો',
    'about.cycle.collect_desc': 'રોજગાર + ચેક-ઇન + નિયોક્તા ડેટા',
    'about.cycle.analyse': 'વિશ્લેષણ કરો',
    'about.cycle.analyse_desc': 'જાળવણી + મેળ ન ખાતો ડેટા + કૌશલ્ય ખાધ',
    'about.cycle.act': 'પગલાં લો',
    'about.cycle.act_desc': 'પ્રોગ્રામ્સ અને પોલિસી નિર્ણયોમાં સુધારો કરો',
    'about.why_title': 'તે શા માટે મહત્વનું છે',
    'about.why.tracking': 'વધુ સારી પરિણામ ટ્રેકિંગ સિસ્ટમ',
    'about.why.feedback': 'ઉદ્યોગ તરફથી મજબૂત પ્રતિસાદ',
    'about.why.development': 'ડેટા-આધારિત કૌશલ્ય વિકાસ',
    'about.final_statement': '“તાલીમના પરિણામોથી લઈને ગુજરાત માટે વધુ સારા નિર્ણયો સુધી.”',
    'header.det_title': 'રોજગાર અને તાલીમ નિયામકની કચેરી',
    'footer.brand_title': 'કૌશલસેતુ – ગુજરાત',
    'footer.brand_desc': 'લાંબા ગાળાનું રોજગાર પરિણામ ટ્રેકિંગ એન્જિન. યુવા રોજગાર સશક્તિકરણ, પ્રદાતા ગુણવત્તા મોનિટર અને રાજ્યવ્યાપી કૌશલ્ય નીતિ માટે ડેટા-આધારિત સિસ્ટમ.',
    'footer.tag': 'ગુજરાત કૌશલ્ય વિકાસ નિયામકની કચેરી',
    'footer.contact_title': 'સત્તાવાર સંપર્ક',
    'footer.address': 'બ્લોક નં. ૧, ૩ જો માળ, ડૉ. જીવરાજ મહેતા ભવન, ગાંધીનગર - ૩૮૨૦૧૦',
    'footer.links_title': 'સરકારી પોર્ટલ',
    'footer.link.state': 'ગુજરાત રાજ્ય પોર્ટલ',
    'footer.link.det': 'DET ગુજરાત પોર્ટલ',
    'footer.link.msde': 'કૌશલ્ય વિકાસ મંત્રાલય (MSDE)',
    'footer.privacy': 'ગોપનીયતા નીતિ',
    'footer.terms': 'નિયમો અને શરતો',
    'footer.help': 'હેલ્પડેસ્ક',
  },
  HI: {
    'platform.title': 'कौशलसेतु',
    'platform.subtitle': 'गुजरात',
    'platform.tagline': '“रोजगार ट्रैकिंग। कौशल निर्माण।”',
    'nav.home': 'होम',
    'nav.about': 'मंच के बारे में',
    'nav.programmes': 'कार्यक्रम',
    'nav.track': 'परिणाम ट्रैक करें',
    'nav.contact': 'संपर्क',
    'nav.login': 'लॉगिन / पंजीकरण',
    'nav.logout': 'लॉगआउट',
    'nav.my_dashboard': 'मेरा डैशबोर्ड',
    'nav.go_to_dashboard': 'डैशबोर्ड पर जाएं',
    'role.trainee': 'प्रशिक्षु',
    'role.employer': 'नियोक्ता',
    'role.provider': 'प्रशिक्षण प्रदाता',
    'role.government': 'सरकारी पोर्टल',
    'role.trainee.action': 'चेक-इन सत्यापित करने के लिए लॉगिन करें',
    'role.employer.action': 'रोजगार सत्यापन एवं फीडबैक',
    'role.provider.action': 'बैच और प्लेसमेंट ट्रैक करें',
    'role.government.action': 'डैशबोर्ड और इंटेलिजेंस देखें',
    'stats.trainees': 'प्रशिक्षु ट्रैक किए गए',
    'stats.retention': '६-महीने का प्रतिधारण',
    'stats.districts': 'कवर किए गए जिले',
    'stats.flagged': 'फ्लैग किए गए कार्यक्रम',
    'gov.india': 'भारत सरकार',
    'gov.gujarat': 'गुजरात सरकार',
    'satyameva': 'सत्यमेव जयते',
    'login.title': 'सुरक्षित लॉगिन',
    'login.welcome': 'अपने रोल-विशिष्ट डैशबोर्ड तक पहुंचने के लिए साइन इन करें।',
    'login.email': 'ईमेल / उपयोगकर्ता नाम',
    'login.password': 'पासवर्ड',
    'login.button': 'प्रमाणित करें',
    'login.forgot': 'पासवर्ड भूल गए?',
    'login.back': 'भूमिका चयन पर वापस जाएं',
    'footer.det': 'रोजगार और प्रशिक्षण निदेशालय (DET), विभाग (DET), गांधीनगर',
    'footer.copy': '© २०२६ कौशलसेतु – गुजरात। सर्वाधिकार सुरक्षित। (सिंथेटिक डेमो साइट)',
    'footer.links': 'गोपनीयता नीति | सेवा की शर्तें | हेल्पडेस्क',
    'home.select_role': 'पोर्टल प्रवेश बिंदु चुनें',
    'home.authorized_login': 'अधिकृत लॉगिन',
    'home.lifecycle_title': 'मंच ट्रैकिंग जीवन चक्र',
    'home.lifecycle_subtitle': 'कौशलसेतु किस प्रकार प्रशिक्षण से रोजगार तक निरंतर ट्रैकिंग करता है',
    'home.metrics_title': 'वर्तमान पारिस्थितिकी तंत्र आँकड़े',
    'home.disclaimer_title': 'सिंथेटिक परियोजना प्रदर्शन नोटिस',
    'home.disclaimer_desc': 'इस साइट पर प्रदर्शित सभी प्रशिक्षु पंजीकरण, कॉर्पोरेट सत्यापन रिकॉर्ड और डैशबोर्ड मेट्रिक्स सिंथेटिक रूप से उत्पन्न मॉक मॉडल हैं। वे गुजरात सरकार द्वारा एकत्र किए गए वास्तविक डेटा का प्रतिनिधित्व नहीं करते हैं।',
    'home.enables_title': 'कौशलसेतु क्या सक्षम बनाता है',
    'home.enables.track': 'ट्रैक',
    'home.enables.track_desc': 'समय के साथ प्रशिक्षु परिणाम',
    'home.enables.verify': 'सत्यापन',
    'home.enables.verify_desc': 'नियोक्ताओं के साथ रोजगार रिकॉर्ड',
    'home.enables.improve': 'सुधार',
    'home.enables.improve_desc': 'वास्तविक फीडबैक के माध्यम से प्रशिक्षण',
    'home.enables.decide': 'निर्णय',
    'home.enables.decide_desc': 'सरकारी डेटा इंटेलिजेंस',
    'step1.title': 'व्यावसायिक प्रशिक्षण',
    'step1.desc': 'स्नातक प्रमाणित आईटीआई/कौशल पाठ्यक्रम पूरा करते हैं।',
    'step2.title': 'रोजगार प्लेसमेंट',
    'step2.desc': 'प्रशिक्षु विभिन्न उद्योगों में कार्यबल में प्रवेश करते हैं।',
    'step3.title': '३-महीने का चेक-इन',
    'step3.desc': 'प्रशिक्षु प्लेसमेंट और वेतन विवरण अपडेट करता है।',
    'step4.title': '६-महीने का चेक-इन',
    'step4.desc': 'प्रतिधारण और भूमिका वृद्धि का सत्यापन।',
    'step5.title': '१२-महीने का चेक-इन',
    'step5.desc': 'दीर्घकालिक स्थिरता ट्रैकिंग पूर्ण।',
    'step6.title': 'नियोक्ता सत्यापन',
    'step6.desc': 'उद्योग एचआर विवरण की पुष्टि करता है और कौशल अंतराल दर्ज करता है।',
    'step7.title': 'सरकारी विश्लेषण',
    'step7.desc': 'DET जिला और प्रदाता परिणामों की निगरानी करता है।',
    'step8.title': 'नीति अनुकूलन',
    'step8.desc': 'कौशल अंतराल के आधार पर पाठ्यक्रम में सुधार किया जाता है।',
    'about.title': 'कौशलसेतु के बारे में',
    'about.subtitle': '“गुजरात के रोजगार-परिणाम पारिस्थितिकी तंत्र को समझना”',
    'about.what_is_desc': 'कौशलसेतु ट्रैक करता है कि प्रशिक्षण के बाद क्या होता है - रोजगार और प्रतिधारण से लेकर नियोक्ता फीडबैक और कौशल अंतराल तक।',
    'about.challenge_title': 'चुनौती',
    'about.challenge.placement': 'प्लेसमेंट ≠ प्रतिधारण',
    'about.challenge.placement_desc': 'नौकरी पाना केवल पहला कदम है।',
    'about.challenge.skills': 'कौशल ≠ हमेशा काम के लिए तैयार',
    'about.challenge.skills_desc': 'कार्यस्थल की आवश्यकताएं बदल सकती हैं।',
    'about.challenge.followup': 'सीमित अनुवर्ती कार्रवाई',
    'about.challenge.followup_desc': 'दीर्घकालिक परिणामों के लिए निरंतर ट्रैकिंग आवश्यक है।',
    'about.solves_title': 'कौशलसेतु इसका समाधान कैसे करता है',
    'about.roles_title': 'एक पारिस्थितिकी तंत्र। चार भूमिकाएँ।',
    'about.role.trainee_desc': 'चेक-इन और रोजगार परिणामों को अपडेट करता है।',
    'about.role.employer_desc': 'रोजगार का सत्यापन करता है और कार्यस्थल फीडबैक देता है।',
    'about.role.provider_desc': 'कार्यक्रम के प्रदर्शन और परिणामों को ट्रैक करता है।',
    'about.role.government_desc': 'बेहतर निर्णयों के लिए एकत्रित खुफिया जानकारी का उपयोग करता है।',
    'about.lifecycle_title': 'डेटा से निर्णय तक',
    'about.cycle.collect': 'संग्रह',
    'about.cycle.collect_desc': 'रोजगार + चेक-इन + नियोक्ता डेटा',
    'about.cycle.analyse': 'विश्लेषण',
    'about.cycle.analyse_desc': 'प्रतिधारण + बेमेल डेटा + कौशल अंतराल',
    'about.cycle.act': 'कार्रवाई',
    'about.cycle.act_desc': 'कार्यक्रमों और नीतिगत निर्णयों में सुधार करें',
    'about.why_title': 'यह क्यों महत्वपूर्ण है',
    'about.why.tracking': 'बेहतर परिणाम ट्रैकिंग प्रणाली',
    'about.why.feedback': 'उद्योग से मजबूत प्रतिक्रिया',
    'about.why.development': 'कौशल विकास',
    'about.final_statement': '“प्रशिक्षण परिणामों से लेकर गुजरात के लिए बेहतर निर्णयों तक।”',
    'header.det_title': 'रोजगार और प्रशिक्षण निदेशालय',
    'footer.brand_title': 'कौशलसेतु – गुजरात',
    'footer.brand_desc': 'दीर्घकालिक व्यावसायिक परिणाम ट्रैकिंग इंजन। युवा रोजगार सशक्तिकरण, प्रदाता गुणवत्ता निगरानी और राज्य स्तरीय कौशल नीति के लिए डेटा-संचालित प्रणाली।',
    'footer.tag': 'गुजरात कौशल विकास निदेशालय',
    'footer.contact_title': 'आधिकारिक संपर्क',
    'footer.address': 'ब्लॉक नंबर १, तीसरी मंजिल, डॉ. जीवराज मेहता भवन, गांधीनगर - ३८२०१०',
    'footer.links_title': 'सरकारी पोर्टल',
    'footer.link.state': 'गुजरात राज्य पोर्टल',
    'footer.link.det': 'DET गुजरात पोर्टल',
    'footer.link.msde': 'कौशल विकास मंत्रालय (MSDE)',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'नियम और शर्तें',
    'footer.help': 'हेल्पडेस्क',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('EN');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
